function getBedAndStorageData() {
return {
	"bedRoomAndStorage": {
		"bedFrames": [
			{
				"prodID": "BSB001",
				"prodName": "Stan Bed Frame",
				"description": "High quality bed frame from the Stans.",
				"price": 9500.89,
				"stock": 11,
				"rentStock": 6,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_1.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "classic"]
			},
			{
				"prodID": "BSB002",
				"prodName": "Woodsoft Blair",
				"description": "Cushion soft headboard and standard wood frame.",
				"price": 8742.00,
				"stock": 21,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_2.jpg",
				"sale": 0,
				"purchases": 8,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "classic"]
			},
			{
				"prodID": "BSB003",
				"prodName": "Fine Oak",
				"description": "Pine wood furnish with classic texture of lumber design.",
				"price": 9312.00,
				"stock": 16,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_3.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["brown", "classic"]
			},
			{
				"prodID": "BSB004",
				"prodName": "Luxotic Master King",
				"description": "King bed with soothing headboard padding and design flow.",
				"price": 9992.23,
				"stock": 11,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_4.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["black", "modern"]
			},
			{
				"prodID": "BSB005",
				"prodName": "Flat Wood Flair",
				"description": "2-person bed and a flat wood frame support for the mattress.",
				"price": 7321.31,
				"stock": 3,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_5.jpg",
				"sale": 5,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSB006",
				"prodName": "Centurian Queen",
				"description": "Total package of descriptions: astonishing, magnificent, wonderful, slick. This futuristic drama of rest days will set you pleasuring sleep.",
				"price": 10090.43,
				"stock": 9,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_6.jpg",
				"sale": 0,
				"purchases": 24,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black", "steel"]
			},
			{
				"prodID": "BSB007",
				"prodName": "Luna Deck",
				"description": "Holds you like a palm of an angel. New design with headboard and frame in one",
				"price": 46788.00,
				"stock": 6,
				"rentStock": 2,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_7.jpg",
				"sale": 0,
				"purchases": 31,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black"]
			},
			{
				"prodID": "BSB008",
				"prodName": "Old Pine King",
				"description": "The grand old duke of york will settle your debts of stress.",
				"price": 7821.24,
				"stock": 5,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_8.jpg",
				"sale": 0,
				"purchases": 15,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSB009",
				"prodName": "Woodraft Master Bed",
				"description": "With pair of drawers on the sides and usable back support for other keeps.",
				"price": 10992.32,
				"stock": 9,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_9.jpg",
				"sale": 0,
				"purchases": 24,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSB010",
				"prodName": "Minimal Grey",
				"description": "Grey contexture of pore texture headboard elaborates minimalism.",
				"price": 6932.09,
				"stock": 2,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bedFrames/bedframe_10.jpg",
				"sale": 10,
				"purchases": 24,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["grey"]
			}

		],
		"mattresses": [
			{
				"prodID": "BSM001",
				"prodName": "Uratex Soft 211",
				"description": "For 2-person use and serve as wonderful comfort to both of you.",
				"price": 2110.22,
				"stock": 31,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_1.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM002",
				"prodName": "Serta Savant",
				"description": "Proud product of Farmington Hills in the line of mattresses.",
				"price": 5210.90,
				"stock": 32,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_2.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM003",
				"prodName": "Uratex Core 312",
				"description": "3-person capacity from Core series of Uratex.",
				"price": 2993.90,
				"stock": 19,
				"rentStock": 1,
				"image": "/bedRoomAndStorage/mattresses/mattress_3.jpg",
				"sale": 60,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM004",
				"prodName": "Serta Perfect",
				"description": "Perfected from foam quality to fabric texture and design.",
				"price": 3123.00,
				"stock": 3,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_4.jpg",
				"sale": 0,
				"purchases": 23,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM005",
				"prodName": "ISR Vantage",
				"description": "Layers of dynamic conditioned foams and materials just to illuminate heaven.",
				"price": 3577.60,
				"stock": 9,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_5.jpg",
				"sale": 0,
				"purchases": 22,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM006",
				"prodName": "Pillow Top Mattress",
				"description": "Plain design with revealing marks of feather comfort.",
				"price": 2412.53,
				"stock": 17,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_6.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM007",
				"prodName": "Spring Mattress Supreme",
				"description": "Thin body with high tests of quality foam.",
				"price": 1623.52,
				"stock": 13,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_7.jpg",
				"sale": 0,
				"purchases": 28,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM008",
				"prodName": "Blueflex Gel Foam",
				"description": "Special layer of blue gel to conduct cool sensation to your body.",
				"price": 5233.90,
				"stock": 5,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_8.jpg",
				"sale": 0,
				"purchases": 26,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["white"]
			},
			{
				"prodID": "BSM009",
				"prodName": "Ultraform Queen Mattress",
				"description": "Queen bed for your master room.",
				"price": 3419.00,
				"stock": 4,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_9.jpg",
				"sale": 0,
				"purchases": 16,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "BSM010",
				"prodName": "Serta Raised Queen",
				"description": "Brand new queen mattress from Serta series.",
				"price": 4299.99,
				"stock": 19,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/mattresses/mattress_10.jpg",
				"sale": 0,
				"purchases": 7,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["white"]
			}
		],
		"wardrobesAndCabinets": [
			{
				"prodID": "BSW001",
				"prodName": "Lumber Slab Wardrobe",
				"description": "2 compartments that fit most of your clothes to be hanged and folded.",
				"price": 10222.86,
				"stock": 9,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_1.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSW002",
				"prodName": "Steel Cabinet",
				"description": "Contains 5 compartment for variety of stuff to contain.",
				"price": 23453.37,
				"stock": 13,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_2.jpg",
				"sale": 10,
				"purchases": 4,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["grey", "steel"]
			},
			{
				"prodID": "BSW003",
				"prodName": "Apple iKeep",
				"description": "Better product ever built with an improved jack and wireless storage. Metallic body and made with plastic to move it like its hot.",
				"price": 34129.68,
				"stock": 4,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_3.jpg",
				"sale": 0,
				"purchases": 24,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["silver", "steel"]
			},
			{
				"prodID": "BSW004",
				"prodName": "0902 Slide Drawer",
				"description": "Creative drawer for casual storage and keeps with 2 compartment technology.",
				"price": 9889.20,
				"stock": 19,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_4.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSW005",
				"prodName": "3Gig Storage",
				"description": "Creative drawer for casual storage and keeps with 3 compartment technology.",
				"price": 10241.80,
				"stock": 5,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_5.jpg",
				"sale": 0,
				"purchases": 23,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSW006",
				"prodName": "Neon Green Multipurpose",
				"description": "All-in-one package from storage to table and other use.",
				"price": 21352.50,
				"stock": 4,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_6.jpg",
				"sale": 0,
				"purchases": 31,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["green", "white", "table"]
			},			
			{
				"prodID": "BSW007",
				"prodName": "White Wood Cabinet",
				"description": "Your desired room cabinet with all your stuffs and fabrics in one storage.",
				"price": 9998.78,
				"stock": 3,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_7.jpg",
				"sale": 0,
				"purchases": 20,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "white", "wood"]
			},
			{
				"prodID": "BSW008",
				"prodName": "Modern Office Archive",
				"description": "Confidential to personal files are now proven secured with this professional drawer.",
				"price": 25899.56,
				"stock": 7,
				"rentStock": 2,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_8.jpg",
				"sale": 0,
				"purchases": 7,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSW009",
				"prodName": "Ikeo Medievel Wardrobe",
				"description": "Stiff greater Ikeo wardrobe has the authority of its highness to use it for public property.",
				"price": 18999.99,
				"stock": 12,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/wardrobes_cabinets/storage_9.jpg",
				"sale": 30,
				"purchases": 5,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			}			
		],
		"bookcasesAndShelves": [
			{
				"prodID": "BSBS001",
				"prodName": "Eleo Bookcase",
				"description": "Unique wowzers design of keeping alternative accessories and not just your fable-lous books.",
				"price": 15533.42,
				"stock": 3,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bookcases_shelves/case_1.jpg",
				"sale": 10,
				"purchases": 23,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black", "wood"]
			},
			{
				"prodID": "BSBS002",
				"prodName": "Fischer Self Shelf ",
				"description": "White motif with alluring motive of altering design to store stuffs in obvious patterns.",
				"price": 12312.40,
				"stock": 29,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bookcases_shelves/case_2.jpg",
				"sale": 0,
				"purchases": 22,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["white", "wood"]
			},
			{
				"prodID": "BSBS003",
				"prodName": "Slant o' Parallel",
				"description": "Not to mention that the root shelf is at the middle with extended frames within its edges.",
				"price": 13122.41,
				"stock": 13,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bookcases_shelves/case_3.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSBS004",
				"prodName": "Checker Shelf",
				"description": "Grid design conspiracy and equalizes stuffs to keep in.",
				"price": 21331.00,
				"stock": 14,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bookcases_shelves/case_4.jpg",
				"sale": 0,
				"purchases": 51,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSBS005",
				"prodName": "Wynplacer 321",
				"description": "Stack in cascade mode with this altering shelf from 3, then 2, and finally 1.",
				"price": 13123.02,
				"stock": 5,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bookcases_shelves/case_5.jpg",
				"sale": 5,
				"purchases": 2,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "BSBS006",
				"prodName": "Fischer Vintage Brown",
				"description": "3-casing brown jumbo version of the Fischer Self Shelf. Just in case the majority needs bigger storage",
				"price": 21344.00,
				"stock": 28,
				"rentStock": 0,
				"image": "/bedRoomAndStorage/bookcases_shelves/case_6.jpg",
				"sale": 0,
				"purchases": 11,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			}
		]
	}
} ;
}
