function getDiningRoomData() {
return {
	"diningRoom": {
		"sets": [
			{
				"prodID": "DS001",
				"prodName": "Shadow 6-Seater Set",
				"description": "This modern dining set with transparent table and shiny leather chairs will suit dark placements.",
				"price": 22992.50,
				"stock": 6,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_1.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["black", "transparent", "shiny", "6-Seater"]
			},
			{
				"prodID": "DS002",
				"prodName": "Alterno 4/6-Seater Set",
				"description": "Alternative style of 6-seater with 1 seat being twin'd together.",
				"price": 22873.80,
				"stock": 12,
				"rentStock": 3,
				"image": "/diningRoom/sets/diningset_2.jpg",
				"sale": 0,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "unique", "4-Seater", "6-Seater"]
			},
			{
				"prodID": "DS003",
				"prodName": "Woody 4-Seater Set",
				"description": "Wooden set with better back seat padding.",
				"price": 20832.09,
				"stock": 17,
				"rentStock": 7,
				"image": "/diningRoom/sets/diningset_3.jpg",
				"sale": 0,
				"purchases": 8,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood", "4-Seater"]
			},
			{
				"prodID": "DS004",
				"prodName": "Guilford 3/5-Seater Set",
				"description": "Choose between 3-5 seating arrangements with this wooden inspired set.",
				"price": 21978.42,
				"stock": 9,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_4.jpg",
				"sale": 5,
				"purchases": 18,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "3-Seater", "5-Seater"]
			},
			{
				"prodID": "DS005",
				"prodName": "Woody 6-Seater Set",
				"description": "6-seater counterpart of the original 4-seater.",
				"price": 21978.42,
				"stock": 9,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_5.jpg",
				"sale": 5,
				"purchases": 18,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "wood", "6-Seater"]
			},
			{
				"prodID": "DS006",
				"prodName": "Negre 6-Seater Set",
				"description": "Western finest set for 6 people only.",
				"price": 20109.89,
				"stock": 10,
				"rentStock": 2,
				"image": "/diningRoom/sets/diningset_6.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "black", "6-Seater"]
			},
			{
				"prodID": "DS007",
				"prodName": "French 3/4-Seater Set",
				"description": "Distinct design through angled perspectives of use. French inspired in France itself.",
				"price": 23241.90,
				"stock": 12,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_7.jpg",
				"sale": 0,
				"purchases": 34,
				"newRelease": true,
				"onDisplay": true,
				"tags": ["black", "french", "3-Seater", "4-Seater"]
			},
			{
				"prodID": "DS008",
				"prodName": "Mahogany 6-Seater Set",
				"description": "Wooden classic style dining set that can suit vacation or rest houses.",
				"price": 19843.55,
				"stock": 1,
				"rentStock": 3,
				"image": "/diningRoom/sets/diningset_8.jpg",
				"sale": 40,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "classic", "6-Seater"]
			},
			{
				"prodID": "DS009",
				"prodName": "Mahogany 4-Seater Set",
				"description": "4-seater alternative to the original.",
				"price": 19543.55,
				"stock": 4,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_9.jpg",
				"sale": 0,
				"purchases": 0,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "classic", "4-Seater"]
			},
			{
				"prodID": "DS010",
				"prodName": "Transitional 6-Seater Set",
				"description": "Cream themed set honed via your wishes.",
				"price": 21532.45,
				"stock": 14,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_10.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["khaki", "cream", "6-Seater"]
			},
			{
				"prodID": "DS011",
				"prodName": "Rustic 8-Seater Set",
				"description": "Double the the typical 4-seating arrangment in this wooden set.",
				"price": 23312.00,
				"stock": 24,
				"rentStock": 5,
				"image": "/diningRoom/sets/diningset_11.jpg",
				"sale": 0,
				"purchases": 11,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood", "8-Seater"]
			},
			{
				"prodID": "DS012",
				"prodName": "Contempo 4-Seater Set",
				"description": "Contemporary as it is for casual guest servings and snack habits.",
				"price": 17593.05,
				"stock": 7,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_12.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "glass", "4-Seater"]
			},
			{
				"prodID": "DS013",
				"prodName": "Von Snow 6-Seater Set",
				"description": "White as snow and table glass.",
				"price": 20734.00,
				"stock": 14,
				"rentStock": 0,
				"image": "/diningRoom/sets/diningset_13.jpg",
				"sale": 0,
				"purchases": 24,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white", "glass", "6-Seater"]
			}
		],
		"chairs": [
			{
				"prodID": "DC001",
				"prodName": "Von Snow",
				"description": "Elegant chair designed for dining purposes.",
				"price": 3212.50,
				"stock": 12,
				"rentStock": 7,
				"image": "/diningRoom/chairs/diningchair_1.jpg",
				"sale": 0,
				"purchases": 26,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["white", "leather"]
			},
			{
				"prodID": "DC002",
				"prodName": "Jepetto's",
				"description": "Once sat by the owner to carve his son Pinocchio.",
				"price": 1431.00,
				"stock": 32,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_2.jpg",
				"sale": 30,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "DC003",
				"prodName": "Maron V",
				"description": "It has the jaggers to potentially move. Contemplated with old payphones and maps.",
				"price": 1798.00,
				"stock": 16,
				"rentStock": 15,
				"image": "/diningRoom/chairs/diningchair_3.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "wood"]
			},
			{
				"prodID": "DC004",
				"prodName": "Hugh Long",
				"description": "High chair like a boss.",
				"price": 2798.40,
				"stock": 14,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_4.jpg",
				"sale": 65,
				"purchases": 2,
				"newRelease": true,
				"onDisplay": true,
				"tags": ["brown", "cushion"]
			},
			{
				"prodID": "DC005",
				"prodName": "Hugh Bent",
				"description": "Bent chair like a boss to lean back in heavenly drama.",
				"price": 2458.30,
				"stock": 13,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_5.jpg",
				"sale": 0,
				"purchases": 15,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "cushion"]
			},
			{
				"prodID": "DC006",
				"prodName": "Deviant Gold",
				"description": "Shiny gold inspired dining chair then a throne for your home.",
				"price": 4551.00,
				"stock": 13,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_6.jpg",
				"sale": 0,
				"purchases": 51,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["gold", "leather", "shiny"]
			},
			{
				"prodID": "DC007",
				"prodName": "Rochet Stripped",
				"description": "Minlimalized architecture still filling its essential structures.",
				"price": 3151.00,
				"stock": 15,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_7.jpg",
				"sale": 20,
				"purchases": 2,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "minimal"]
			},
			{
				"prodID": "DC008",
				"prodName": "Oakley",
				"description": "Originally crafted as its name. Especial for office and school use.",
				"price": 2002.99,
				"stock": 21,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_8.jpg",
				"sale": 0,
				"purchases": 35,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["grey", "cushion"]
			},
			{
				"prodID": "DC009",
				"prodName": "Villa Faux",
				"description": "Handcrafted Indian chair and high back padding",
				"price": 1935.00,
				"stock": 16,
				"rentStock": 8,
				"image": "/diningRoom/chairs/diningchair_9.jpg",
				"sale": 0,
				"purchases": 7,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["orange", "leather"]
			},
			{
				"prodID": "DC010",
				"prodName": "Aprilia Dark Red",
				"description": "Upholstered dining chair and typical type.",
				"price": 3412.80,
				"stock": 14,
				"rentStock": 0,
				"image": "/diningRoom/chairs/diningchair_10.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["red", "cushion"]
			}
		],
		"tables": [
			{
				"prodID": "DT001",
				"prodName": "Silvero",
				"description": "Silver-gloss finish and can uphold 6-seater arrangement.",
				"price": 9892.00,
				"stock": 13,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_1.jpg",
				"sale": 0,
				"purchases": 26,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["silver", "6-Seater"]
			},
			{
				"prodID": "DT002",
				"prodName": "Queen Anne",
				"description": "Royal resemblance of first rulings of the York.",
				"price": 8790.00,
				"stock": 11,
				"rentStock": 6,
				"image": "/diningRoom/tables/diningtable_2.jpg",
				"sale": 30,
				"purchases": 34,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood", "6-Seater"]
			},
			{
				"prodID": "DT003",
				"prodName": "Madero Square",
				"description": "Perfect for two, sides front of you.",
				"price": 6000.00,
				"stock": 2,
				"rentStock": 2,
				"image": "/diningRoom/tables/diningtable_3.jpg",
				"sale": 0,
				"purchases": 2,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["brown", "2-Seater"]
			},
			{
				"prodID": "DT004",
				"prodName": "Espresso Copper",
				"description": "Firm glass built and firm wooden copper frames.",
				"price": 9022.90,
				"stock": 24,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_4.jpg",
				"sale": 0,
				"purchases": 34,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["glass", "wood", "6-Seater"]
			},
			{
				"prodID": "DT005",
				"prodName": "Modern Metroplus",
				"description": "Metropolitan design that says your comfort standards.",
				"price": 10005.38,
				"stock": 18,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_5.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "6-Seater"]
			},
			{
				"prodID": "DT006",
				"prodName": "Esque Pino",
				"description": "Traditional wooden style table for varieties of uses.",
				"price": 9122.90,
				"stock": 21,
				"rentStock": 14,
				"image": "/diningRoom/tables/diningtable_6.jpg",
				"sale": 0,
				"purchases": 48,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "6-Seater"]
			},
			{
				"prodID": "DT007",
				"prodName": "Phillippe",
				"description": "Dining table designed by Oly Studio. Round and multipurpose.",
				"price": 7433.00,
				"stock": 17,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_7.jpg",
				"sale": 0,
				"purchases": 3,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood", "2-Seater"]
			},
			{
				"prodID": "DT008",
				"prodName": "Bassett Dunhill",
				"description": "Mirror rectangular glass dining table in walnut.",
				"price": 8992.00,
				"stock": 6,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_8.jpg",
				"sale": 0,
				"purchases": 13,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "glass", "6-Seater"]
			},
			{
				"prodID": "DT009",
				"prodName": "Stockholm",
				"description": "Rectangular dining table with brick furnace stand.",
				"price": 7999.99,
				"stock": 15,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_9.jpg",
				"sale": 0,
				"purchases": 20,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black", "brown", "6-Seater"]
			},
			{
				"prodID": "DT010",
				"prodName": "Bristol",
				"description": "Wooden Bristol dining table for contemporary design.",
				"price": 8872.00,
				"stock": 21,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_10.jpg",
				"sale": 0,
				"purchases": 9,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black", "brown", "6-Seater"]
			},
			{
				"prodID": "DT011",
				"prodName": "Cavalleria Rusticana",
				"description": "Classic wood dining table by the Rustanica family.",
				"price": 7221.92,
				"stock": 31,
				"rentStock": 0,
				"image": "/diningRoom/tables/diningtable_11.jpg",
				"sale": 40,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "wood", "6-Seater"]
			}
		]
	}
} ;
}