function getDisplayAndDecorData() {
return {
	"displayAndDecors": {
		"curtains": [
			{
				"prodID": "DDC001",
				"prodName": "Shady Blue",
				"description": "Ever classic then modern experience of covering your windows.",
				"price": 123.50,
				"stock": 12,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_1.jpg",
				"sale": 23,
				"purchases": 25,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["blue"]
			},
			{
				"prodID": "DDC002",
				"prodName": "Eclipse Bellagio",
				"description": "Casually design yet binds the stream of sunlight as astonishing.",
				"price": 110.00,
				"stock": 34,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_2.jpg",
				"sale": 0,
				"purchases": 43,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown"]
			},
			{
				"prodID": "DDC003",
				"prodName": "JC Penny Eclipse",
				"description": "Collaborated by the penny daughters with the aussie style of house living.",
				"price": 234.60,
				"stock": 23,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_3.jpg",
				"sale": 0,
				"purchases": 15,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "blue"]
			},
			{
				"prodID": "DDC004",
				"prodName": "Starlit BluSky",
				"description": "Shones diamonds in the sky of the day and live blue .",
				"price": 145.30,
				"stock": 21,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_4.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["blue", "stars"]
			},
			{
				"prodID": "DDC005",
				"prodName": "Matte black",
				"description": "Less black, much brighter vibrance.",
				"price": 120.00,
				"stock": 16,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_5.jpg",
				"sale": 20,
				"purchases": 15,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black"]
			},
			{
				"prodID": "DDC006",
				"prodName": "Jasmine Falls",
				"description": "Such a beautiful white flower attachments that comforts the nature of heaven.",
				"price": 176.86,
				"stock": 12,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_6.jpg",
				"sale": 0,
				"purchases": 13,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["white", "flowers"]
			},
			{
				"prodID": "DDC007",
				"prodName": "Marquee Cinnabar",
				"description": "Maroon-orange inspired curtain that also resembles traditional welcome curtains.",
				"price": 190.32,
				"stock": 34,
				"rentStock": 3,
				"image": "/displayAndDecors/curtains/curtain_7.jpg",
				"sale": 10,
				"purchases": 13,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["red", "orange"]
			},
			{
				"prodID": "DDC008",
				"prodName": "Faux Silk-drapes",
				"description": "Casually design yet binds the stream of sunlight as astonishing.",
				"price": 231.90,
				"stock": 14,
				"rentStock": 0,
				"image": "/displayAndDecors/curtains/curtain_8.jpg",
				"sale": 40,
				"purchases": 23,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["grey"]
			},
			{
				"prodID": "DDC009",
				"prodName": "Velvet Curtains 12",
				"description": "12 feet curtain drape with mustard motif design.",
				"price": 200.00,
				"stock": 16,
				"rentStock": 5,
				"image": "/displayAndDecors/curtains/curtain_9.jpg",
				"sale": 0,
				"purchases": 0,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["yellow", "mustard", "12-feet"]
			},
			{
				"prodID": "DDC010",
				"prodName": "Thermal backed",
				"description": "Curtains spotlight and rosy red inpired for your pleasures.",
				"price": 245.32,
				"stock": 4,
				"rentStock": 5,
				"image": "/displayAndDecors/curtains/curtain_10.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["red"]
			}
		],
		"figurines": [
			{
				"prodID": "DDF001",
				"prodName": "Buddha 12-inch",
				"description": "Traditional buddhist idol of Buddha. Yet popular to the multi-cultured.",
				"price": 123.50,
				"stock": 35,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_1.jpg",
				"sale": 0,
				"purchases": 42,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["gold", "buddhist", "religion"]
			},
			{
				"prodID": "DDF002",
				"prodName": "Wooden Adarna",
				"description": "Adapted from the local legend of the Philippines and counterpart of phoenix.",
				"price": 199.89,
				"stock": 25,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_2.jpg",
				"sale": 30,
				"purchases": 29,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "brown", "bird"]
			},
			{
				"prodID": "DDF003",
				"prodName": "Twin Kitties",
				"description": "Very very cutie cute kitties for your cute home.",
				"price": 155.20,
				"stock": 34,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_3.jpg",
				"sale": 0,
				"purchases": 34,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["ceramic", "cat", "white"]
			},
			{
				"prodID": "DDF004",
				"prodName": "Little Angel",
				"description": "Heavenly angel staring at the skies of the wonder of your home.",
				"price": 132.90,
				"stock": 21,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_4.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["ceramic", "white"]
			},
			{
				"prodID": "DDF005",
				"prodName": "Money Cat",
				"description": "The most famous display believed to be giving luck and charm to living and business.",
				"price": 210.45,
				"stock": 41,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_5.jpg",
				"sale": 0,
				"purchases": 47,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["gold", "cat"]
			},
			{
				"prodID": "DDF006",
				"prodName": "Parrot display",
				"description": "The colorful bird of life now sits on your home.",
				"price": 189.00,
				"stock": 33,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_6.jpg",
				"sale": 0,
				"purchases": 24,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["ceramic", "colorful"]
			},
			{
				"prodID": "DDF007",
				"prodName": "Jade Deer",
				"description": "Deer statue made of synthetic jade and ceramic.",
				"price": 199.00,
				"stock": 21,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_7.jpg",
				"sale": 0,
				"purchases": 15,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["ceramic", "green"]
			},
			{
				"prodID": "DDF008",
				"prodName": "Turquiose Ceramic Owl",
				"description": "Perfect for variety of other seamless colorful displays.",
				"price": 345.45,
				"stock": 15,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_8.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["ceramic", "blue"]
			},
			{
				"prodID": "DDF009",
				"prodName": "Flying Cloud Ship",
				"description": "Ship in a bottle will set sail towards the waves of desires.",
				"price": 431.89,
				"stock": 8,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_9.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["bottle", "ship"]
			},
			{
				"prodID": "DDF010",
				"prodName": "Wailing Dragon",
				"description": "Chinese tibet brass dragon holding its power ball.",
				"price": 320.67,
				"stock": 14,
				"rentStock": 0,
				"image": "/displayAndDecors/figurines/figurine_10.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brass", "chinese", "tibet"]
			}			
		],
		"carpets": [
			{
				"prodID": "DDCP001",
				"prodName": "Antique Persian",
				"description": "A traditional carpet from the middle east now here and retailed.",
				"price": 590.90,
				"stock": 32,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_1.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "silk"]
			},
			{
				"prodID": "DDCP002",
				"prodName": "Badi Al Saudia",
				"description": "The arabian nights proud and finest carpet of those sands of time.",
				"price": 590.90,
				"stock": 25,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_2.jpg",
				"sale": 0,
				"purchases": 15,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "silk"]
			},
			{
				"prodID": "DDCP003",
				"prodName": "Fun Squareception",
				"description": "Modern rich design of carpet. Repetitive pattern of squares and stiffs.",
				"price": 451.00,
				"stock": 19,
				"rentStock": 4,
				"image": "/displayAndDecors/carpets/carpet_3.jpg",
				"sale": 0,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["grey", "square"]
			},
			{
				"prodID": "DDCP004",
				"prodName": "Turkish Oushak",
				"description": "From turkey with stuff red and khaki patterns.",
				"price": 412.00,
				"stock": 5,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_4.jpg",
				"sale": 35,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["red", "brown"]
			},
			{
				"prodID": "DDCP005",
				"prodName": "Mini Modern Rugs x5",
				"description": "Complete package of 5 uses of this when you purchase.",
				"price": 489.23,
				"stock": 8,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_5.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["grey", "brown"]
			},
			{
				"prodID": "DDCP006",
				"prodName": "Direwolf coat",
				"description": "Synthetic skin of the creature in northern wilds of Winterfell.",
				"price": 678.00,
				"stock": 2,
				"rentStock": 2,
				"image": "/displayAndDecors/carpets/carpet_6.jpg",
				"sale": 0,
				"purchases": 39,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["grey"]
			},
			{
				"prodID": "DDCP007",
				"prodName": "Strip brown",
				"description": "Color lines and simple brown themed carpet.",
				"price": 275.90,
				"stock": 27,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_7.jpg",
				"sale": 40,
				"purchases": 11,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "colorful"]
			},
			{
				"prodID": "DDCP008",
				"prodName": "Maui Fett",
				"description": "Circle of fun is the pattern and not illusion.",
				"price": 167.74,
				"stock": 17,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_8.jpg",
				"sale": 0,
				"purchases": 15,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["brown", "circle"]
			},
			{
				"prodID": "DDCP009",
				"prodName": "Autumn bars and stripes",
				"description": "This fall is for you together with this special rug.",
				"price": 103.43,
				"stock": 21,
				"rentStock": 0,
				"image": "/displayAndDecors/carpets/carpet_9.jpg",
				"sale": 0,
				"purchases": 11,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["brown", "blue"]
			},
			{
				"prodID": "DDCP010",
				"prodName": "Aleppo drape",
				"description": "Inspired in Syria like other tradional arabian carpets.",
				"price": 210.21,
				"stock": 8,
				"rentStock": 6,
				"image": "/displayAndDecors/carpets/carpet_10.jpg",
				"sale": 0,
				"purchases": 5,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "red"]
			}
		],
		"mirrors": [
			{
				"prodID": "DDM001",
				"prodName": "5262 Varnish Morrior",
				"description": "Typical mirrors to display on anywhere in the part of your house.",
				"price": 90.90,
				"stock": 39,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_1.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown"]
			},
			{
				"prodID": "DDM002",
				"prodName": "Federal Wall Mirror",
				"description": "Dressing room-style mirror and a square structure.",
				"price": 110.21,
				"stock": 27,
				"rentStock": 6,
				"image": "/displayAndDecors/mirrors/mirror_2.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black", "yellow"]
			},
			{
				"prodID": "DDM003",
				"prodName": "Lund Stand Mirror",
				"description": "Modern stand mirror on the floor. Height is aroung 6-feet.",
				"price": 290.00,
				"stock": 27,
				"rentStock": 10,
				"image": "/displayAndDecors/mirrors/mirror_3.jpg",
				"sale": 0,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown"]
			},
			{
				"prodID": "DDM004",
				"prodName": "Oval Gold Mirror",
				"description": "Legendary mirror from the evil witch of poisoned apple pies and milk.",
				"price": 210.32,
				"stock": 21,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_4.jpg",
				"sale": 10,
				"purchases": 25,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["gold", "round", "circle"]
			},
			{
				"prodID": "DDM005",
				"prodName": "Silva Mira",
				"description": "Silver mirror with royal diamond-like design curves.",
				"price": 189.00,
				"stock": 17,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_5.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["silver", "royal"]
			},
			{
				"prodID": "DDM006",
				"prodName": "Windisch 99231O",
				"description": "Facial mirror with concave lens having a magnification value of 2000x.",
				"price": 157.27,
				"stock": 23,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_6.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["gold", "face"]
			},
			{
				"prodID": "DDM007",
				"prodName": "Chic Satin Nickel Round",
				"description": "Re-envisioned viewing of your self as multiple reflections cast serenity and personality.",
				"price": 234.23,
				"stock": 3,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_7.jpg",
				"sale": 0,
				"purchases": 31,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["silver", "round", "circle"]
			},
			{
				"prodID": "DDM008",
				"prodName": "Z Mirror",
				"description": "Clamped design ceramic with gloss finishing for the frame.",
				"price": 153.90,
				"stock": 36,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_8.jpg",
				"sale": 0,
				"purchases": 10,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "ceramic"]
			},
			{
				"prodID": "DDM009",
				"prodName": "Deknudt Stand Mirror",
				"description": "Silver stand mirror from German luxury properties.",
				"price": 559.89,
				"stock": 12,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_9.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["silver"]
			},
			{
				"prodID": "DDM010",
				"prodName": "St. Caress Mirror",
				"description": "Mirror related to the last property used by St. Caress. It was said she saw the ghost of her twin sister in here.",
				"price": 213.67,
				"stock": 1,
				"rentStock": 0,
				"image": "/displayAndDecors/mirrors/mirror_10.jpg",
				"sale": 50,
				"purchases": 0,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brass"]
			}			
		]		
	}
} ;
}