function getLivingRoomData() {
return {
	"livingRoom": {
		"sofas": [
			{
				"prodID": "LS001",
				"prodName": "A3 Airszen",
				"description": "Soft as its name to be a comfort within your living. Style adapts to its environment.",
				"price": 9500.89,
				"stock": 11,
				"rentStock": 6,
				"image": "/livingRoom/sofas/sofa_1.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "classic"]
			},
			{
				"prodID": "LS002",
				"prodName": "Ghandu Borsz",
				"description": "Originated from western malis to preserve its native background and design. Feel the culture exerted from this piece.",
				"price": 9700.00,
				"stock": 8,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_2.jpg",
				"sale": 0,
				"purchases": 17,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["rainbow", "colorful", "pink", "modern"]
			},
			{
				"prodID": "LS003",
				"prodName": "Lyon Snow",
				"description": "White comfort with the essence of royal property. Enduces state of depression.",
				"price": 10312.60,
				"stock": 4,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_3.jpg",
				"sale": 70,
				"purchases": 24,
				"newRelease": true,
				"onDisplay": true,
				"tags": ["white", "royal", "modern"]
			},
			{
				"prodID": "LS004",
				"prodName": "9 Morris",
				"description": "Viking inspired structure brings forth the breeze of excitement of the coming land.",
				"price": 9994.89,
				"stock": 0,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_4.jpg",
				"sale": 0,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["grey", "classic"]
			},
			{
				"prodID": "LS005",
				"prodName": "Crispen Espo D",
				"description": "The professional Crispen Espo collaborates home material and fashion to liberate furniture design. One of his pieces are this featured",
				"price": 12412.05,
				"stock": 5,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_5.jpg",
				"sale": 0,
				"purchases": 31,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["black", "sofa bed", "modern"]
			},
			{
				"prodID": "LS006",
				"prodName": "Tusken Blu Sofa",
				"description": "More seatings, more companions in a row. This 4-seater item is as modern to be used.",
				"price": 13900.00,
				"stock": 4,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_6.jpg",
				"sale": 10,
				"purchases": 17,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["blue", "modern", "4-seater"]
			},
			{
				"prodID": "LS007",
				"prodName": "Oldie Leather",
				"description": "Classic sofa for the casual office facilities or other uses.",
				"price": 6000.00,
				"stock": 24,
				"rentStock": 9,
				"image": "/livingRoom/sofas/sofa_7.jpg",
				"sale": 0,
				"purchases": 9,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["brown", "classic"]
			},
			{
				"prodID": "LS008",
				"prodName": "Cream Beam 2A",
				"description": "Joyous to homes and other events to handle your entertainment and comfort.",
				"price": 10205.40,
				"stock": 20,
				"rentStock": 3,
				"image": "/livingRoom/sofas/sofa_8.jpg",
				"sale": 0,
				"purchases": 22,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["white"]
			},
			{
				"prodID": "LS009",
				"prodName": "Stellar Sofa 3",
				"description": "3-seater yet accomodates richness to its environment.",
				"price": 7899.99,
				"stock": 11,
				"rentStock": 7,
				"image": "/livingRoom/sofas/sofa_9.jpg",
				"sale": 0,
				"purchases": 6,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["white", "black", "3-seater"]
			},
			{
				"prodID": "LS010",
				"prodName": "Blanc Unde",
				"description": "Synthetic texture with systematic structure of comfort.",
				"price": 10040.10,
				"stock": 0,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_10.jpg",
				"sale": 20,
				"purchases": 9,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["dark grey"]
			},
			{
				"prodID": "LS011",
				"prodName": "Corner Convertable Sofa",
				"description": "Sofa and bed at the same time, for personal use and love.",
				"price": 12040.00,
				"stock": 0,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_11.jpg",
				"sale": 0,
				"purchases": 27,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["white", "sofa bed"]
			},
			{
				"prodID": "LS012",
				"prodName": "Adel Sofa",
				"description": "Looks like red velvet with extra love for seating.",
				"price": 15365.60,
				"stock": 20,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_12.jpg",
				"sale": 0,
				"purchases": 22,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["red", "3-seater"]
			},
			{
				"prodID": "LS013",
				"prodName": "Chaise lounge",
				"description": "Smoothest, slick style to consider for your purple desires.",
				"price": 14987.82,
				"stock": 18,
				"rentStock": 5,
				"image": "/livingRoom/sofas/sofa_13.jpg",
				"sale": 5,
				"purchases": 27,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["purple", "violet", "modern"]
			},
			{
				"prodID": "LS014",
				"prodName": "Parsons Wooden Sofa",
				"description": "This aussie import is behind the creation of Parsons Garnet and is frame composed of pine woods.",
				"price": 14025.00,
				"stock": 11,
				"rentStock": 0,
				"image": "/livingRoom/sofas/sofa_14.jpg",
				"sale": 0,
				"purchases": 20,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["orange", "wood", "pine", "australia", "imported"]
			}
		],
		"tvStands": [
			{
				"prodID": "LT001",
				"prodName": "Alvotainment Stand",
				"description": "Handles from any sets of players with its modern approach.",
				"price": 3411.82,
				"stock": 15,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_1.jpg",
				"sale": 0,
				"purchases": 9,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["black", "3-cased"]
			},
			{
				"prodID": "LT002",
				"prodName": "2211 Pine Glass Rack",
				"description": "Wood and glass architecture resembling presence of natural materials.",
				"price": 5674.34,
				"stock": 11,
				"rentStock": 3,
				"image": "/livingRoom/tvStands/tvstand_2.jpg",
				"sale": 0,
				"purchases": 2,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["wood", "glass", "brown", "3-cased"]
			},
			{
				"prodID": "LT003",
				"prodName": "500 Brown Wood",
				"description": "Wonderful for total entertainment storages like CDs, cassettes to contain within its drawers available in two pairs.",
				"price": 5900.90,
				"stock": 24,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_3.jpg",
				"sale": 45,
				"purchases": 6,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "brown", "drawers", "multi-cased"]
			},
			{
				"prodID": "LT004",
				"prodName": "Entertainment Beam 2000",
				"description": "A long journey of your own devices and stuffs to settle on this wonderful set of furniture. Paralled structure has accomodated space for your own.",
				"price": 6132.00,
				"stock": 16,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_4.jpg",
				"sale": 0,
				"purchases": 14,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "glass", "brown", "multi-cased"]
			},
			{
				"prodID": "LT005",
				"prodName": "Dwell SZ",
				"description": "Alternate strips on side that reduces solid casing within your devices.",
				"price": 5557.00,
				"stock": 42,
				"rentStock": 5,
				"image": "/livingRoom/tvStands/tvstand_5.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["wood", "brown", "3-cased"]
			},
			{
				"prodID": "LT006",
				"prodName": "3144 Header Ent",
				"description": "Elongated frame structure with furnished, massive casing handles your loads of stuffs.",
				"price": 6989.99,
				"stock": 33,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_6.jpg",
				"sale": 10,
				"purchases": 31,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["wood", "brown", "black", "3-cased"]
			},
			{
				"prodID": "LT007",
				"prodName": "99 Oak TV Stand",
				"description": "Casual entertainment for your simple life.",
				"price": 2390.89,
				"stock": 31,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_7.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "black", "2-cased"]
			},
			{
				"prodID": "LT008",
				"prodName": "Nassau TV Stand",
				"description": "4-casing compartment has its common design pattern of matrix implementation, and not to forget the top.",
				"price": 5233.00,
				"stock": 19,
				"rentStock": 5,
				"image": "/livingRoom/tvStands/tvstand_8.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "black", "5-cased"]
			},
			{
				"prodID": "LT009",
				"prodName": "Walnut niche",
				"description": "Glass thickness has reached beyond its form to exteriorize the inner wooden case.",
				"price": 8978.99,
				"stock": 4,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_9.jpg",
				"sale": 0,
				"purchases": 8,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["wood", "glass", "2-cased"]
			},
			{
				"prodID": "LT010",
				"prodName": "1010 Khaki Pirk",
				"description": "Another classic theme of entertainment stands with enough compartments to lay and contain other stuffs.",
				"price": 7134.00,
				"stock": 0,
				"rentStock": 2,
				"image": "/livingRoom/tvStands/tvstand_10.jpg",
				"sale": 0,
				"purchases": 18,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "brown", "5-cased"]
			},
			{
				"prodID": "LT011",
				"prodName": "BlackGlass TV Cabinet",
				"description": "Black tint glass and sequence holes in the back frame.",
				"price": 8233.31,
				"stock": 6,
				"rentStock": 0,
				"image": "/livingRoom/tvStands/tvstand_11.jpg",
				"sale": 0,
				"purchases": 11,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["glass", "black", "3-cased"]
			}
		],
		"centerTables": [
			{
				"prodID": "LC001",
				"prodName": "Oakwood Table",
				"description": "Perfect for casual wood accessories and entertainment.",
				"price": 902.00,
				"stock": 11,
				"rentStock": 2,
				"image": "/livingRoom/centerTables/centertable_1.jpg",
				"sale": 0,
				"purchases": 19,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "brown"]
			},
			{
				"prodID": "LC002",
				"prodName": "Glass Tempered Center",
				"description": "Glass support with wooden frames for visible outlook.",
				"price": 889.79,
				"stock": 8,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_2.jpg",
				"sale": 10,
				"purchases": 17,
				"newRelease": true,
				"onDisplay": false,
				"tags": ["wood", "glass", "brown"]
			},
			{
				"prodID": "LC003",
				"prodName": "Pandemonium Center Coil",
				"description": "The coil-like holder below looks like a stove and a glass support at top.",
				"price": 1011.20,
				"stock": 4,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_3.jpg",
				"sale": 0,
				"purchases": 20,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "glass", "brown"]
			},
			{
				"prodID": "LC004",
				"prodName": "Stark Glass Twin Wood",
				"description": "Two equilateral cross wooden frame for the glass support and dimension is about 50cmx50cm.",
				"price": 2998.90,
				"stock": 3,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_4.jpg",
				"sale": 0,
				"purchases": 28,
				"newRelease": false,
				"onDisplay": true,
				"tags": ["wood", "glass", "brown"]
			},
			{
				"prodID": "LC005",
				"prodName": "Down Crown Majest",
				"description": "The silver crown-shaped holder is just the main attraction but the glass is greater.",
				"price": 2460.10,
				"stock": 7,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_5.jpg",
				"sale": 0,
				"purchases": 32,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "glass", "silver", "brown"]
			},
			{
				"prodID": "LC006",
				"prodName": "Contemporary Style",
				"description": "Condominium style center table and a pure modern tech of slouching drawer on it.",
				"price": 2689.23,
				"stock": 7,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_6.jpg",
				"sale": 0,
				"purchases": 54,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "brown"]
			},
			{
				"prodID": "LC007",
				"prodName": "Three frame Peria",
				"description": "This has been supported with lovely strong pine wood frames as a trio for the maintain the structure of the table.",
				"price": 3412.66,
				"stock": 5,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_7.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "black"]
			},
			{
				"prodID": "LC008",
				"prodName": "Darth Table",
				"description": "Varied property of sith empire and has a slant hold ergonomic for your delicate stuffs.",
				"price": 3412.66,
				"stock": 5,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_8.jpg",
				"sale": 0,
				"purchases": 21,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "black"]
			},
			{
				"prodID": "LC009",
				"prodName": "Half Hollow Table",
				"description": "Re-innovate your keeps under your center table with this majestic piece of furniture.",
				"price": 3221.41,
				"stock": 17,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_9.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "black"]
			},
			{
				"prodID": "LC0010",
				"prodName": "Circle Glass Branch",
				"description": "This we consider the most awesome design with glass and table as turned out to be abstracted and maintained function.",
				"price": 3221.41,
				"stock": 17,
				"rentStock": 0,
				"image": "/livingRoom/centerTables/centertable_10.jpg",
				"sale": 0,
				"purchases": 12,
				"newRelease": false,
				"onDisplay": false,
				"tags": ["wood", "black"]
			}
		]
	}
} ;
}